#!/usr/bin/env node
/**
 * Build-time image optimisation for static export.
 * Generates responsive AVIF/WebP/JPEG variants + manifest for srcset wiring.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import sharp from "sharp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const IMAGES_DIR = path.join(ROOT, "public", "images");
const OPT_DIR = path.join(IMAGES_DIR, "opt");
const SOURCE_DIR = path.join(ROOT, "image-sources");
const MANIFEST_TS = path.join(ROOT, "src", "data", "image-manifest.ts");

/** Images referenced by the site (skip orphans). */
const USED_BASES = new Set([
  "hero-home",
  "og-default",
  "cruise-port",
  "old-town",
  "roque-nublo",
  "volcano",
  "dunes",
  "village",
  "island",
  "coast",
  "food",
  "wine",
  "beach",
  "market",
  "compare",
  "highlights",
  "photography",
  // legacy fallbacks still in public/images
  "hercules",
  "santiago",
  "pilgrimage",
  "castle",
  "fishing",
  "galicia-landscape",
]);

/** Hero/guide assets — wider breakpoints. */
const HERO_BASES = new Set([
  "hero-home",
  "photography",
  "og-default",
  "compare",
  "cruise-port",
  "roque-nublo",
  "volcano",
  "island",
  "dunes",
  "highlights",
]);

const CARD_WIDTHS = [320, 480, 640, 800];
const HERO_WIDTHS = [640, 960, 1280, 1920];
const OG_SIZE = { width: 1200, height: 630 };

const QUALITY = { avif: 62, webp: 78, jpeg: 82 };

async function ensureDir(dir) {
  await fs.mkdir(dir, { recursive: true });
}

function widthsForBase(base, sourceWidth) {
  const pool = HERO_BASES.has(base)
    ? [...new Set([...CARD_WIDTHS, ...HERO_WIDTHS])].sort((a, b) => a - b)
    : CARD_WIDTHS;
  return pool.filter((w) => w <= sourceWidth);
}

async function processImage(base) {
  const livePath = path.join(IMAGES_DIR, `${base}.jpg`);
  const sourcePath = path.join(SOURCE_DIR, `${base}.jpg`);

  // Archive full-resolution original before overwriting
  try {
    await fs.access(livePath);
    try {
      await fs.access(sourcePath);
    } catch {
      await fs.copyFile(livePath, sourcePath);
    }
  } catch {
    // already archived from prior run
  }

  const inputPath = (await fs.access(sourcePath).then(() => true).catch(() => false))
    ? sourcePath
    : livePath;

  const meta = await sharp(inputPath).metadata();
  const sourceWidth = meta.width ?? 1920;
  const sourceHeight = meta.height ?? 1080;
  const widths = widthsForBase(base, sourceWidth);
  const maxWidth = Math.min(sourceWidth, HERO_BASES.has(base) ? 1920 : 800);

  const entry = {
    base,
    width: sourceWidth,
    height: sourceHeight,
    fallbackWidth: maxWidth,
    fallbackHeight: Math.round((sourceHeight / sourceWidth) * maxWidth),
    widths,
    formats: ["avif", "webp", "jpg"],
  };

  if (base === "og-default") {
    entry.og = { width: OG_SIZE.width, height: OG_SIZE.height };
  }

  for (const w of widths) {
    const h = Math.round((sourceHeight / sourceWidth) * w);
    const pipeline = sharp(inputPath).resize(w, h, { fit: "inside", withoutEnlargement: true });

    await pipeline.clone().avif({ quality: QUALITY.avif, effort: 4 }).toFile(path.join(OPT_DIR, `${base}-${w}w.avif`));
    await pipeline.clone().webp({ quality: QUALITY.webp }).toFile(path.join(OPT_DIR, `${base}-${w}w.webp`));
  }

  // Compressed JPEG fallback via temp file (never overwrite input in place)
  const jpgOut = path.join(IMAGES_DIR, `${base}.jpg`);
  const jpgTmp = path.join(IMAGES_DIR, `${base}.jpg.tmp`);
  await sharp(inputPath)
    .resize(maxWidth, null, { fit: "inside", withoutEnlargement: true })
    .jpeg({ quality: QUALITY.jpeg, mozjpeg: true })
    .toFile(jpgTmp);
  await fs.rename(jpgTmp, jpgOut);

  if (base === "og-default") {
    for (const fmt of ["avif", "webp", "jpg"]) {
      const out = path.join(OPT_DIR, `${base}-og1200.${fmt}`);
      let p = sharp(inputPath).resize(OG_SIZE.width, OG_SIZE.height, { fit: "cover", position: "centre" });
      if (fmt === "avif") p = p.avif({ quality: QUALITY.avif, effort: 4 });
      else if (fmt === "webp") p = p.webp({ quality: QUALITY.webp });
      else p = p.jpeg({ quality: QUALITY.jpeg, mozjpeg: true });
      await p.toFile(out);
    }
    entry.ogSrc = `/images/opt/og-default-og1200.jpg`;
  }

  return entry;
}

async function removeOrphans() {
  for (const orphan of ["family", "private"]) {
    for (const dir of [IMAGES_DIR, SOURCE_DIR]) {
      try {
        await fs.unlink(path.join(dir, `${orphan}.jpg`));
        console.log(`  removed orphan ${orphan}.jpg`);
      } catch {
      }
    }
  }
}

async function writeManifest(manifest) {
  const sorted = Object.fromEntries(
    Object.entries(manifest).sort(([a], [b]) => a.localeCompare(b)),
  );
  const body = `/** Auto-generated by scripts/optimize-images.mjs — do not edit */\nexport const imageManifest = ${JSON.stringify(sorted, null, 2)} as const;\n\nexport type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];\n`;
  await fs.writeFile(MANIFEST_TS, body);
}

async function main() {
  console.log("Optimising site images…\n");
  await ensureDir(OPT_DIR);
  await ensureDir(SOURCE_DIR);

  const manifest = {};
  for (const base of [...USED_BASES].sort()) {
    try {
      process.stdout.write(`  ${base}… `);
      manifest[base] = await processImage(base);
      const optFiles = manifest[base].widths.length * 2 + 1;
      console.log(`✓ (${optFiles} variants + fallback)`);
    } catch (err) {
      console.log(`✗ ${err.message}`);
    }
  }

  await removeOrphans();
  await writeManifest(manifest);

  const optStat = await fs.readdir(OPT_DIR);
  let totalOpt = 0;
  for (const f of optStat) {
    const s = await fs.stat(path.join(OPT_DIR, f));
    totalOpt += s.size;
  }
  let totalJpg = 0;
  for (const base of USED_BASES) {
    try {
      const s = await fs.stat(path.join(IMAGES_DIR, `${base}.jpg`));
      totalJpg += s.size;
    } catch {
    }
  }

  console.log(`\nDone. ${optStat.length} files in opt/ (${(totalOpt / 1024 / 1024).toFixed(1)} MB)`);
  console.log(`JPEG fallbacks: ${(totalJpg / 1024 / 1024).toFixed(1)} MB`);
  console.log(`Manifest → src/data/image-manifest.ts`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
