/** Auto-generated by scripts/optimize-images.mjs — do not edit */
export const imageManifest = {
  "beach": {
    "base": "beach",
    "width": 8461,
    "height": 4653,
    "fallbackWidth": 800,
    "fallbackHeight": 440,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "castle": {
    "base": "castle",
    "width": 5534,
    "height": 8301,
    "fallbackWidth": 800,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "coast": {
    "base": "coast",
    "width": 2318,
    "height": 685,
    "fallbackWidth": 800,
    "fallbackHeight": 236,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "compare": {
    "base": "compare",
    "width": 3509,
    "height": 5265,
    "fallbackWidth": 1920,
    "fallbackHeight": 2881,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "cruise-port": {
    "base": "cruise-port",
    "width": 17575,
    "height": 4040,
    "fallbackWidth": 1920,
    "fallbackHeight": 441,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "dunes": {
    "base": "dunes",
    "width": 4608,
    "height": 3456,
    "fallbackWidth": 1920,
    "fallbackHeight": 1440,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "fishing": {
    "base": "fishing",
    "width": 2400,
    "height": 1920,
    "fallbackWidth": 800,
    "fallbackHeight": 640,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "food": {
    "base": "food",
    "width": 3072,
    "height": 2304,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "galicia-landscape": {
    "base": "galicia-landscape",
    "width": 4160,
    "height": 2340,
    "fallbackWidth": 800,
    "fallbackHeight": 450,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hercules": {
    "base": "hercules",
    "width": 5484,
    "height": 3656,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "hero-home": {
    "base": "hero-home",
    "width": 16544,
    "height": 4337,
    "fallbackWidth": 1920,
    "fallbackHeight": 503,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "highlights": {
    "base": "highlights",
    "width": 5599,
    "height": 7361,
    "fallbackWidth": 1920,
    "fallbackHeight": 2524,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "island": {
    "base": "island",
    "width": 3000,
    "height": 1431,
    "fallbackWidth": 1920,
    "fallbackHeight": 916,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "market": {
    "base": "market",
    "width": 2400,
    "height": 1800,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "og-default": {
    "base": "og-default",
    "width": 8641,
    "height": 4626,
    "fallbackWidth": 1920,
    "fallbackHeight": 1028,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ],
    "og": {
      "width": 1200,
      "height": 630
    },
    "ogSrc": "/images/opt/og-default-og1200.jpg"
  },
  "old-town": {
    "base": "old-town",
    "width": 8285,
    "height": 5655,
    "fallbackWidth": 800,
    "fallbackHeight": 546,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "photography": {
    "base": "photography",
    "width": 16544,
    "height": 4337,
    "fallbackWidth": 1920,
    "fallbackHeight": 503,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "pilgrimage": {
    "base": "pilgrimage",
    "width": 4128,
    "height": 3096,
    "fallbackWidth": 800,
    "fallbackHeight": 600,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "roque-nublo": {
    "base": "roque-nublo",
    "width": 8763,
    "height": 9341,
    "fallbackWidth": 1920,
    "fallbackHeight": 2047,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "santiago": {
    "base": "santiago",
    "width": 5456,
    "height": 3638,
    "fallbackWidth": 800,
    "fallbackHeight": 533,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "village": {
    "base": "village",
    "width": 2336,
    "height": 3504,
    "fallbackWidth": 800,
    "fallbackHeight": 1200,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "volcano": {
    "base": "volcano",
    "width": 3368,
    "height": 1536,
    "fallbackWidth": 1920,
    "fallbackHeight": 876,
    "widths": [
      320,
      480,
      640,
      800,
      960,
      1280,
      1920
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  },
  "wine": {
    "base": "wine",
    "width": 1080,
    "height": 805,
    "fallbackWidth": 800,
    "fallbackHeight": 596,
    "widths": [
      320,
      480,
      640,
      800
    ],
    "formats": [
      "avif",
      "webp",
      "jpg"
    ]
  }
} as const;

export type ImageManifestEntry = (typeof imageManifest)[keyof typeof imageManifest];
